# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-01 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('modifier', models.IntegerField()),
                ('score', models.IntegerField()),
                ('free', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ability_boost_flaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier', models.IntegerField()),
                ('free', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ancestry_feat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Anchestry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1500)),
                ('hit_points', models.IntegerField()),
                ('size', models.CharField(max_length=15)),
                ('languages', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Heritage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('anchestry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Anchestry')),
            ],
        ),
        migrations.CreateModel(
            name='Special_ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('anchestry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Anchestry')),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('anchestry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Anchestry')),
            ],
        ),
        migrations.AddField(
            model_name='ancestry_feat',
            name='anchestry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Anchestry'),
        ),
        migrations.AddField(
            model_name='ability_boost_flaw',
            name='anchestry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Anchestry'),
        ),
        migrations.AddField(
            model_name='ability_boost_flaw',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheet.Ability'),
        ),
    ]
