# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-01 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0002_remove_ability_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='free',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
