# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-01 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0004_remove_ability_boost_flaw_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability_boost_flaw',
            name='free',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
